name: Laravel Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy .env.example to .env
        run: cp ./src/.env.example ./src/.env

      - name: Generate Laravel app key
        run: |
          docker-compose -f docker-compose.yml up -d --build
          sleep 15 # wait for containers to be ready
          docker-compose exec app php artisan key:generate

      - name: Run Laravel migrations
        run: docker-compose exec app php artisan migrate

      - name: Run tests (optional)
        run: docker-compose exec app php artisan test

      - name: Shut down Docker
        if: always()
        run: docker-compose down
