name: Laravel Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-ce-version: stable
        docker-compose-version: v2

    - name: Start containers
      run: |
        docker compose -f docker-compose.yml up -d --build

    - name: Wait for MySQL
      run: sleep 15

    - name: Run migrations
      run: |
        docker exec laravel_appp php artisan migrate --force

    - name: Run tests
      run: |
        docker exec laravel_appp php artisan test
